#!/bin/sh
#
# Simple openAMDC init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:     openamdc_6379
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    openAMDC data structure server
# Description:          openAMDC data structure server
### END INIT INFO

OPENAMDCPORT=6379
EXEC=/usr/local/bin/openamdc-server
CLIEXEC=/usr/local/bin/openamdc-cli

PIDFILE=/var/run/openamdc_${OPENAMDCPORT}.pid
CONF="/etc/openamdc/${OPENAMDCPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting openAMDC server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $OPENAMDCPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for openAMDC to shutdown ..."
                    sleep 1
                done
                echo "openAMDC stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
